# Sect 26: Linear Algebra

## Objectives

- Be able to explain the difference(s) between vectors, matrices, tensors, etc. and their dimensionality.

- Understand the the difference between the shape and size of an array

- Discuss linear algebra operations with numpy

- Learn about using linear algebra to solve systems of equations

- If there's time: walking through Solution for [Solving Systems of Linear Equations with NumPy - Lab](https://learn.co/tracks/data-science-career-v2/module-4-a-complete-data-science-project-using-multiple-regression/section-26-linear-algebra/solving-systems-of-linear-equations-with-numpy-lab)

### Resources:
- Learn: [Motivation for Linear Algebra](https://learn.co/tracks/data-science-career-v2/module-4-a-complete-data-science-project-using-multiple-regression/section-26-linear-algebra/motivation-for-linear-algebra-in-data-science)

- www.desmos.com (linear equation grapher)



In [1]:
# Cohort package
!pip install -U fsds_100719
from fsds_100719.imports import *

fsds_1007219  v0.4.45 loaded.  Read the docs: https://fsds.readthedocs.io/en/latest/ 


In [2]:
# Imports needed for this notebook
import numpy as np

# What & Why of Linear Algebra

- Study of "vector spaces"; relationship of **linear** relationships
- Uses vectors, matrices, and tensors
- Mapping & dimensionality (PCA)
- Used in lots of ML applications

We'll try to put abstract ideas into the formalism of linear algebra
 - images/pixels
 - language (NLP)

# Different Tensors

## Scalars, Vectors, Matrices: It's all about the dimension

![different_tensors.png](images/different_tensors.png)

## Creating with NumPy

In [2]:
# Scalar
s = np.arange(1)
display(s)

array([0])

In [4]:
# Vector
v = np.arange(4)
display(v)
# print(v)

# Other ways to define vector
x = np.linspace(-np.pi, np.pi, 10)
display(x)

array([0, 1, 2, 3])

[0 1 2 3]


array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [7]:
# Matrix
M0 = np.arange(4 * 2)
display(M0)
M = np.arange(4 * 2).reshape((4, 2))
display(M)
print(M)

array([0, 1, 2, 3, 4, 5, 6, 7])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [8]:
# 3D Tensor
T_3d = np.arange(4 * 2 * 3).reshape((4, 2, 3))
display(T_3d)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

### Indexing with NumPy

#### Different parts of a vector

In [9]:
# For Vectors
display(v[1:4])  # second to fourth element. Element 5 is not included
display(v[::2])  # every other element
display(v[:])    # print the whole vector
display(v[::-1]) # reverse the vector!

array([1, 2, 3])

array([0, 2])

array([0, 1, 2, 3])

array([3, 2, 1, 0])

#### Different parts of a matrix

In [11]:
display(M)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
display(M[0, 0])   # element at first row and first column

0

In [12]:
display(M[-1, -1]) # elemenet last row and last column 

7

In [13]:
display(M[0, :])   # first row and all columns

array([0, 1])

In [14]:
display(M[:, 0])   # all rows and first column 

array([0, 2, 4, 6])

In [15]:
display(M[:])      # all rows and all columns

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

#### Different parts of a tensor

In [19]:
display(T_3d)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [16]:
print(T_3d[0])      # 2D: First matrix

[[0 1 2]
 [3 4 5]]


In [20]:
print(T_3d[0, 0])   # 1D: First matrix's first vector

[0 1 2]


In [21]:
print(T_3d[0,0, 0]) # 0D: First matrix's first vector's first element

0


In [22]:
print(T_3d[0, 0, :])  # 1D: first matrix, first vector, all elements

[0 1 2]


In [25]:
display(T_3d)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [23]:
print(T_3d[0, :, 0])  # 1D: first matrix, all the vectors, just the fist element

[0 3]


In [24]:
print(T_3d[0, :, 1:]) # 1D: first matrix, all the vectors, all elements after the first

[[1 2]
 [4 5]]


# Basic Properties

## Shape

Can help us know the dimensions and size

In [27]:
print('Scalar:')
s = np.array(100)
print(s)
display(s.shape)
display(s.size)

Scalar:
100


()

1

In [28]:
print('Vector:')
print(v)
display(v.shape)
display(v.size)

Vector:
[0 1 2 3]


(4,)

4

In [31]:
print('Matrix:')
print(M)
display(M.shape)
display(M.size)

Matrix:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


(4, 2)

8

In [32]:
print('3D Tensor:')
print(T_3d)
display(T_3d.shape)
display(T_3d.size)

3D Tensor:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


(4, 2, 3)

24

## Transpose

![transpose_tensors.png](images/transpose_tensors.png)

In [33]:
display(M.shape)
print(M)

display(M.T.shape)
# Alternative to: M.T
print(np.transpose(M))

(4, 2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


(2, 4)

[[0 2 4 6]
 [1 3 5 7]]


In [35]:
display(T_3d.shape)
print(T_3d)

display(T_3d.T.shape)
print(T_3d.T)

display(T_3d.T.T.shape)
print(T_3d.T.T)

(4, 2, 3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


(3, 2, 4)

[[[ 0  6 12 18]
  [ 3  9 15 21]]

 [[ 1  7 13 19]
  [ 4 10 16 22]]

 [[ 2  8 14 20]
  [ 5 11 17 23]]]


(4, 2, 3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [36]:
# Imports for this notebook
import numpy as np

# Combining Tensors

> Note: NumPy is pretty smart when you combine tensors; it will attempt to combine even if the dimensions don't match. This is called broadcasting & you can read about it in the documentation (https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)[https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html].

In [37]:
A = np.arange(3*2).reshape(3,2)
B = 10 * np.arange(3*2).reshape(3,2)

print('A:\n', A)
print()
print('B:\n', B)

A:
 [[0 1]
 [2 3]
 [4 5]]

B:
 [[ 0 10]
 [20 30]
 [40 50]]


## Addition

In [38]:
A = np.arange(3*2).reshape(3,2)
B = 10 * np.arange(3*2).reshape(3,2)

print('A:\n', A)
print()
print('B:\n', B)

A:
 [[0 1]
 [2 3]
 [4 5]]

B:
 [[ 0 10]
 [20 30]
 [40 50]]


In [39]:
# We can add up the same dimensions! (elementwise)
A + B

array([[ 0, 11],
       [22, 33],
       [44, 55]])

In [40]:
# Broadcasting: We can even add scalars to the whole array (as you might expect)
A + 100

array([[100, 101],
       [102, 103],
       [104, 105]])

## What happens when we have different dimensions? Broadcasting happens

In [43]:
# 3-by-2 add 1-by-2
x = 100*np.arange(2).reshape(2)
print(x)
print('Size:',x.shape)
print()
print(A)
print()

print(A + x)

[  0 100]
Size: (2,)

[[0 1]
 [2 3]
 [4 5]]

[[  0 101]
 [  2 103]
 [  4 105]]


In [46]:
# 3-by-2 add 3-by-2
print(A)
print()
x = 100*np.arange(3*2).reshape(3,2)
print(x)
print('Size:',x.shape)
print()
print(A + x)

[[0 1]
 [2 3]
 [4 5]]

[[  0 100]
 [200 300]
 [400 500]]
Size: (3, 2)

[[  0 101]
 [202 303]
 [404 505]]


In [48]:
# 3-by-2 add 2-by-3 --> Will this work?
x = 100*np.arange(2*3).reshape(2,3)
print(x)
print('Size:',x.shape)
print()
print(A + x)

[[  0 100 200]
 [300 400 500]]
Size: (2, 3)



ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

## Multiplication (Hadamard Product & Dot Product)

### Hadamard Product

Result: Same dimensions (after broadcasting)

Like addition, but multiply the elements together. This however isn't very common.

In [49]:
print('A:\n', A.shape)
print(A)
print()
print('B:\n', B.shape)
print(B)

A:
 (3, 2)
[[0 1]
 [2 3]
 [4 5]]

B:
 (3, 2)
[[ 0 10]
 [20 30]
 [40 50]]


In [50]:
print(A * B)

[[  0  10]
 [ 40  90]
 [160 250]]


In [52]:
# 3-by-2 add 1-by-2
print(A)
x = 100*np.arange(2).reshape(2)
print(x)
print('Size:',x.shape)
print()
print(A * x)

[[0 1]
 [2 3]
 [4 5]]
[  0 100]
Size: (2,)

[[  0 100]
 [  0 300]
 [  0 500]]


In [54]:
# 3-by-2 add 3-by-2
print(A)
x = 100*np.arange(3*2).reshape(3,2)
print(x)
print('Size:',x.shape)
print()
print(A * x)

[[0 1]
 [2 3]
 [4 5]]
[[  0 100]
 [200 300]
 [400 500]]
Size: (3, 2)

[[   0  100]
 [ 400  900]
 [1600 2500]]


In [55]:
# 3-by-2 add 2-by-3 --> Will this work?
print(A)

x = x = 100*np.arange(3*2).reshape(2,3)
print(x)
print('Size:',x.shape)
print()
print(A * x)

[[0 1]
 [2 3]
 [4 5]]
[[  0 100 200]
 [300 400 500]]
Size: (2, 3)



ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

### Dot Product

Result: (m-by-n) DOT (n-by-p) ==> (m-by-p)

$$A \cdot B = C$$

Likely the most common operation when we think of "multiplying" matrices.

In [56]:
print('A:\n', A.shape)
print(A)
print()

A:
 (3, 2)
[[0 1]
 [2 3]
 [4 5]]



In [57]:
print('B:\n', B.shape)
print(B)
print()

B:
 (3, 2)
[[ 0 10]
 [20 30]
 [40 50]]



In [58]:
C = B.T
print('C:\n', C.shape)
print(C)

C:
 (2, 3)
[[ 0 20 40]
 [10 30 50]]


In [60]:
display(A)
# display(B)
display(C)

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[ 0, 20, 40],
       [10, 30, 50]])

  𝐴  must have the same number of dimensions as  𝐵  has rows.

### Summary of Dot Product.
- When using the dot product, the number of columns in the first matrix must be equal the number of rows in the second matrix.

- We basically take the a column from B and transpose  it and perform broadcasted multiplication with A.

- end shape is # of rows from A and number of columns from B.


$$ A = 
   \left[ {\begin{array}{cc}
   A_{1,1}& A_{1,2} \\
   A_{2,1}& A_{2,2}  \\
   A_{3,1} & A_{3,2} \\
  \end{array} } \right] 
$$

$$ B = 
   \left[ {\begin{array}{cc}
   B_{1,1}&  B_{1,2} \\
   B_{2,1} & B_{2,2} \\
  \end{array} } \right] 
$$

$$ C = 
  \left[ {\begin{array}{cc}
   A_{1,1}* B_{1,1}+ A_{1,2}*B_{2,1} & A_{1,1}* B_{1,2}+ A_{1,2}*B_{2,2} \\
   A_{2,1}* B_{1,1}+ A_{2,2}*B_{2,1} & A_{2,1}* B_{1,2}+ A_{2,2}*B_{2,2} \\
   A_{3,1}* B_{1,1}+ A_{3,2}*B_{2,1} & A_{3,1}* B_{1,2}+ A_{3,2}*B_{2,2} \\
  \end{array} } \right]
$$


This rule applies for a chain of matrix multiplications.  The number of columns in one matrix in the chain must match the number of rows in the following matrix in the chain. The intuition for the matrix multiplication is that you calculate the dot product between each row in matrix $A$ with each column in matrix $B$. For example, you can step down rows of column $A$ and multiply each with column 1 in $B$ to give the scalar values in column 1 of $C$.

This is made clear with the following worked example between two matrices.


$$
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6  \\
   7 & 8 & 9 \\
   10 & 11 & 12 \\
  \end{array} } \right] \times
    \left[ {\begin{array}{cc}
   2 & 7 \\
   1 & 2 \\
   3 & 6 \\
  \end{array} } \right] =
   \left[ {\begin{array}{cc}
   2*1 + 1*2 + 3*3  & 7*1+2*2+6*3\\
   2*4+1*5+3*6 & 7*4+2*5+6*6 \\
   2*7+1*8+3*9 & 7*7+2*8+6*9 \\
   2*10+1*11+3*12 & 7*10+2*11+6*12 \\
  \end{array} } \right] =
    \left[ {\begin{array}{cc}
   13 & 29 \\
   31 & 74  \\
   49 & 119 \\
   67 & 164 \\
  \end{array} } \right] 
$$


Let's define above matrices and see how to achieve this in Python and Numpy using the `.dot()` method :

```python
# matrix dot product
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[2, 7], [1, 2], [3, 6]])

C = A.dot(B)

print(A, '\ndot', '\n', B, '\n = \n', C)
```

In [59]:
# All the ways you can do the dot product
Z = np.dot(A, C)
Z = A.dot(C)
Z = A @ C

print(Z.shape)
print(Z)

(3, 3)
[[ 10  30  50]
 [ 30 130 230]
 [ 50 230 410]]


In [ ]:
# 3-by-2 add 2-by-1
x = 100*np.arange(3).reshape(3)
print(x)
print('Size:',x.shape)
print()
print(A @ x)

### Cross Product

Produces another tensor of the same shape (Note broadcasting can still work)

In [61]:
print(A[:,0])
print(A[:,1])
print()

[0 2 4]
[1 3 5]



In [62]:
print('result:', np.cross(A[:,0],A[:,1]))

result: [-2  4 -2]


# Manipulating Matrices (Identity & Inverse)

## Identity Matrix

Square matrix of diagonal 1's, rest are 0's

In [63]:
I5 = np.eye(5)
print(I5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


When multiplying (dot product), you always get the same matrix (note that still has be compatible shape)

In [64]:
A = np.arange(5*5).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [65]:
print(I5 @ A)
print()
print(A @ I5)
print()
is_equal = (I5 @ A) == (A @ I5)
print('Both are the same:')
print(is_equal)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]

Both are the same:
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


## Inverse Matrix

Remember that we can't divide by a matrix, but we can do something similar by finding an **inverse matrix**

In [66]:
# Define two arrays
X = np.array([1,-2,3,2,-5,10,0,0,1]).reshape(3,3)
print(X)
print()
Y = np.array([5,-2,5,2,-1,4,0,0,1]).reshape(3,3)
print(Y)

[[ 1 -2  3]
 [ 2 -5 10]
 [ 0  0  1]]

[[ 5 -2  5]
 [ 2 -1  4]
 [ 0  0  1]]


In [67]:
# What happens when these are multiplied?
print(X @ Y)
print()
print(Y @ X)

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


We can also find the inverse of a matrix with NumPy

In [68]:
A = np.array([4,2,1,4,8,3,1,1,0]).reshape(3,3)
# Finding the inverse matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.3 -0.1  0.2]
 [-0.3  0.1  0.8]
 [ 0.4  0.2 -2.4]]


In [69]:
# Note the rounding
print(A @ A_inv)

[[ 1.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [-1.66533454e-16  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17 -1.38777878e-17  1.00000000e+00]]


However, not all matrices have an inverse

In [70]:
A = np.arange(9).reshape(3,3)
print(A)
print()
print(np.linalg.inv(A))

[[0 1 2]
 [3 4 5]
 [6 7 8]]



LinAlgError: Singular matrix

In [71]:
# Imports needed for notebook
import numpy as np

# Solving Systems of Equations

Solving a system of equations can take a lot of work

$$ x - 2y + 3z = 9 $$
$$ 2x - 5y + 10z = 4 $$
$$ 0x + 0y + 6z = 0 $$

But we can make it easier by writing it in matrix form

$$ 
\begin{pmatrix} 
    1 & -2 & 3 \\
    2 & -5 & 10 \\
    0 & 0 & 6
\end{pmatrix}
\cdot
\begin{pmatrix} 
    x \\
    y \\
    z
\end{pmatrix}
=
\begin{pmatrix} 
    9 \\
    4 \\
    0
\end{pmatrix}
$$

We can think of this in the abstract:
$$ A \cdot X = B $$
$$ A^{-1} \cdot A \cdot X = A^{-1} \cdot B $$
$$ I \cdot X = A^{-1} \cdot B $$
$$ X = A^{-1} \cdot B $$

## Using NumPy

In [1]:
# Define the system's matrices
A = np.array([
    [1, -2,  3],
    [2, -5, 10],
    [0,  0,  6]
])

B = np.array([9,4,0]).reshape(3,1)
print('A:')
print(A)
print()
print('B:')
print(B)

A:
[[ 1 -2  3]
 [ 2 -5 10]
 [ 0  0  6]]

B:
[[9]
 [4]
 [0]]


In [2]:
# Find the inverse
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 5.         -2.          0.83333333]
 [ 2.         -1.          0.66666667]
 [ 0.          0.          0.16666667]]


In [3]:
# Solutions:
solution = A_inv @ B
print(solution)

[[37.]
 [14.]
 [ 0.]]


In [4]:
# Checking solutions:


print('x - 2y + 3z = 9')
print(f'{solution[0][0]} + {-2*solution[1][0]} + {3*solution[2][0]}')
print(solution[0][0] + -2*solution[1][0] + 3*solution[2][0])
print()

print('2x - 5y + 10z = 4')
print(f'{2*solution[0][0]} + {-5*solution[1][0]} + {10*solution[2][0]}')
print(2*solution[0][0] + -5*solution[1][0] + 10*solution[2][0])
print()

print('0x + 0y + 6z = 0')
print(f'{0*solution[0][0]} + {0*solution[1][0]} + {6*solution[2][0]}')
print(0*solution[0][0] + 0*solution[1][0] + 6*solution[2][0])
print()

x - 2y + 3z = 9
37.0 + -28.0 + 0.0
9.0

2x - 5y + 10z = 4
74.0 + -70.0 + 0.0
4.0

0x + 0y + 6z = 0
0.0 + 0.0 + 0.0
0.0



## Linear Regression w/ Systems of Equations

> We'll find that this is actually computationally expensive for large systems 😭